### ISSUE TITLE
Specific version of Python 3

### ISSUE THREAD

**Issue by dodgerblue11** [jmpu/NoiseScope#1]
Hello, specifically what version of Python 3 was used for this? I wanted to use this implementation for testing purposes and first tried Python 3.8, however noticed that in the requirements.txt, data_classes is only required for less than or =Python 3.6. I then tried to pip install requirements.txt with Python 3.6.9, however then had issues with incompatibility between the versions for bleach and html5lib. Is there helpful information I could have with regards to Python version? Thanks!

**Comment by jmpu** [comment]
Hi thanks for your interests. We used Python 3.6.5. In fact, could you try to remove bleach and html5lib, I don't think those two libraries are necessary for the code to run. I did a pip squeeze on the virtual env so some libraries might be non-necessary. Thanks for pointing it out. I will update the requirement.txt soon.
